# Generated by Django 5.1.7 on 2025-04-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('CEO', models.CharField(max_length=50)),
                ('established_at', models.CharField(max_length=50)),
            ],
        ),
    ]
