# Generated by Django 5.1.7 on 2025-04-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
                ('athor', models.CharField(max_length=50)),
            ],
        ),
    ]
